### PR TITLE
Matts branch

### PR DESCRIPTION
**Pull request by mwlluis**
added gigs

### CODE REVIEW

**Comment by NoleCore** [comment]
Hey is this latest version on the server?

**Comment by mwlluis** [comment]
i just changed the trixies link, all of the dates thru la are there, im going to ftp it to the server now

**Comment by mwlluis** [comment]
since there was a ticketweb link in the fb event page i just changed the link to that instead so that it takes you directly to the ticketstore, im uploading this now to the server

**Comment by mwlluis** [comment]
alright its up there on the server, gigs-mar18.html, looks good to me, check it out and put it live

**Pull request closed without merging**
